[tools]
"cargo:git-delta" = "latest"
"cargo:sheldon" = "latest"
chezmoi = "2.69.3"
fd = "latest"
go = "1.24.0"
node = "22.14.0"
ripgrep = "latest"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[env]
_.file = ".env"
